#!/bin/sh
#
# Starts status leds.
#

start() {
	echo 128 > /sys/class/leds/pwm:green:user/brightness
	echo 0 > /sys/class/leds/pwm:red:user/brightness

}
stop() {
	echo 128 > /sys/class/leds/pwm:red:user/brightness
	echo 0 > /sys/class/leds/pwm:green:user/brightness
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
